### PR TITLE
Add support for a few more paper sizes

### PR DESCRIPTION
**Pull request by GencoreOperative**
Adding a few new paper sizes verified by http://www.papersizes.org/a-sizes-in-pixels.htm.

Also resolved the A7 size which was swapped round (width/height).

### CODE REVIEW

**Comment by nbudin** [comment]
Thanks, and sorry about the A7 issue!

**Comment by GencoreOperative** [comment]
No worries, I'll be testing and using this app for a project so hopefully
can provide some feedback like this.

**Comment by nbudin** [comment]
Are there additional PRs you have cooking?  I'm happy to make a release, but I'd prefer to do one big one, so if there's additional stuff you have that's not quite ready to go I'll wait to do that.

**Comment by GencoreOperative** [comment]
Yes, sorry I should have made my intention clear.

I plan to add command line argument support for configurable margins. I
might also want to look at header and footer support but it is not
essential.

As a minimum expect one more PR later this week.

Thank you :)

**Pull request merged**
